app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Review(db.Model):

    __tablename__ = 'reviews'

    id = db.Column(db.Integer,primary_key = True)
    movie_id = db.Column(db.Integer)
    movie_title = db.Column(db.String)
    image_path = db.Column(db.String)
    movie_review = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_review(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_reviews(cls,id):
        reviews = Review.query.filter_by(movie_id=id).all()
        return reviews


    def save_review(self):
        Review.all_reviews.append(self)


    @classmethod
    def clear_reviews(cls):
        Review.all_reviews.clear()

    @classmethod
    def get_reviews(cls,id):

        response = []

        for review in cls.all_reviews:
            if review.movie_id == id:
                response.append(review)

        return response

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))

    def __repr__(self):
        return f'User {self.username}'
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def is_authenticated(self):
        return True

    def is_active(self): # line 37
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    # Required for administrative interface
    def __unicode__(self):
        return self.username

    




class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class ReviewForm(FlaskForm):

    title = StringField('Review title',validators=[Required()])
    review = TextAreaField('Movie review', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
	bio = TextAreaField('Tell us about you.',validators = [Required()])
	submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

photos = UploadSet('photos',IMAGES)
def create_app(config_name):
    app = Flask(__name__)

def create_app(config_name):
    app = Flask(__name__)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    # configure UploadSet
    configure_uploads(app,photos)
    

    # Will add the views and forms

    # Registering the blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
   

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required, current_user
from . import main
from .. import db, photos
# from ..request import get_quote
# from ..models import User, Post, Comment, Subscriber
# from .forms import PostForm, CommentForm, UpdateProfile, SubscribeForm
# from .. email import mail_message
@main.route('/')
def index():
 title = 'Home'
#   posts = Post.get_posts()
#   quote = get_quote()
 return render_template('index.html', title = title)

@main.route('/search')
def search():
 title = 'Home'
#   posts = Post.get_posts()
#   quote = get_quote()
 return render_template('search.html', title = title)


@main.route('/first')
def first():
 title = 'Home'
#   posts = Post.get_posts()
#   quote = get_quote()
 return render_template('first.html', title = title)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/first.html
  {% extends 'base.html'%}
  {% import 'macros.html' as macro%}

  {% block styles%}
  {{ super() }}
  <link href="https://fonts.googleapis.com/css?family=Advent+Pro&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="animate.css">
  <link rel="stylesheet" href="{{url_for('static',filename='css/animate.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename='css/hover.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="static/js/shop.js"></script>


  {% endblock %}


{% block content %}


 <div class="container-fluid animated zoomInUp">

    <ul id="nav-bar">
      <li><a href="">Shop</a></li>
      <li><a href="#contact">Contact</a></li>
      <li><a href="#about">About Us</a></li>
      <li><a href="index.html" class="active">Home</a></li>
    </ul>

    <div class="row">
      <div class="col-md-8">

        <div class="row">
          <div class="col-md-8" id="va">
           <img src="static/images/max2.jpg" id="lo" style="width: 100%;height: 50%; margin-top: 200px; margin-left: 100px;">

           <img src="static/images/max.png" id="loo" style="width: 100%;height: 50%; margin-top: 200px; margin-left: 100px;">

           <img src="static/images/max3.jpg" id="l" style="width: 100%;height: 50%; margin-top: 200px; margin-left: 100px;">

         </div>

       </div>

       <div class="row">
        <div class="col-md-8">
          <img src="static/images/max3.jpg" onmouseover="this.src='static/images/max.png '" onmouseout="this.src='static/images/max3.jpg'" onmouseover="this.src='static/images/max3.jpg'"/ style="width: 600px;height: 400px; margin-top: 400px;">

        </div>


      </div>
      <div class="row">
        <div class="col-md-8">
         <img src="static/images/max.png" style="width: 700px;height: 800px; margin-top: 200px; width: 600px;height: 400px;">
       </div>

     </div>

   </div>
   <div class="col-md-4" style="margin-top: 80px;">

    <div class="me">
     <h2>Classic Nubuck P</h2>
     <h3> ALLROAD </h3><br>
     <h4>sh 195,00</h4>
     <p>Perforated Nubuck upper / Canvas lining with new leather reinforcement / Quilted nappa leather heel / Waxed laces / Metallic rivets and eyelets / Nubuk flag with embossed logo / Exclusively designed outsole / MADE IN ITALY</p>
     <select style="padding-top: 10px;padding-bottom: 10px; background-color:black;color: white; border-radius: 5px;">
      <option value="chose ur size">chose ur size</option>
      <option value="39">39</option>
      <option value="40">40</option>
      <option value="40">41</option>
      <option value="40">42</option>
      <option value="40">43</option>
      <option value="40">44</option>
    </select>






    <div class="pae">
      <a href="index.html"><img src="static/images/4.png" style="width: 20px;height: 20px"></a><a href="second.html"><img src="static/images/3.jpeg" style="width: 20px;height: 20px; margin-left:200px;"></a></div>


      <a href="#slider-image-1" class="dot1">GREEN</a>
      <a href="#slider-image-2" class="dot2">BLUE</a>
      <a href="#slider-image-3" class="dot3">RED</a>

    </div>

  </div>

</div>

</di>

    Title:<input id="title" type="text">
Price:<input id="price" type="number">
<button onClick="fun()">Add to Cart </button>

<div>
<p><b>Cart Info</b></p>
</div>





</div>
<button type="submit" class="btn btn-black" id="order">PLACE YOUR ORDER</button>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% import 'macros.html' as macro%}
{% extends 'base.html'%}

  {% block styles%}
  {{ super() }}
  <link href="https://fonts.googleapis.com/css?family=Advent+Pro&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="animate.css">
  <link rel="stylesheet" href="{{url_for('static',filename='css/animate.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename='css/hover.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="static/js/custom.js"></script>
 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCWTIlluowDL-X4HbYQt3aDw_oi2JP0Krc&sensor=false"></script>
  <script src="static/js/map.js"></script>


  {% endblock %}


{% block content %}
  
  <div class="container-fluid">
    
 <h2  class=" animated zoomIn">
      <a href="/"><img src="/static/images/y.jpg"  style="width: 200px;height: 100px;"></a>
    </h2>
    <img class="animated zoomIn" src="static/images/yeezy-black.png" alt="black yeezys">
    

  <h1 class="head3"><h2 style="text-align: center;font-family: 'Luckiest Guy', cursive; letter-spacing: 4px; font-size: 3.5em; font-weight: bolder">O<span style="color: crimson">U</span>R<span style="color: crimson">COLLECTION</span></h2></h1>

         
    <span class="border"></span>
    <br><br><br>
<div class="container">
  <div class="row">
  <div class="col-lg-4">
      <img src="/static/images/nike.jpeg" id="slideimg1"/>
      <p class="button-holder">NIKE</p>
      </div>
      <div class="col-lg-4">
      <img src="/static/images/adidas.jpeg" id="slideimg2"/>
      <p class="button-holder">ADIDAS</p>
      </div>
      <div class="col-lg-4">
      <img src="/static/images/puma.png" id="slideimg3"/>
      <p class="button-holder">PUMA</p>

      </div>
      </div> 
</div>

<!--------------------------------------------Personality--------------------------------- -->
  <div id="Personality"class="container">

<!-- LOGO -->

    <div class="row justify-content-center">
      <div class="col-md-2 top-margin-small">
        <!-- <img src="/static/images/kingjosh.jpeg" alt="logo" style="margin-right: 1000px;"> -->
      </div>
    </div>

<!-- First Step (Enter Name) -->

    <div class="text-center" id="first-step">
      <h1>MY-SHOES<br>Personality Customize</h1>
      <p class="lead">Hi There! Let's start with your name.</p>
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <form class="form-horizontal" role="form" id="nameForm">
            <div class="form-group">
              <input class="form-control" type="text" id="username" placeholder="Enter your name" required>
            </div>
            <input type="submit" class="btn btn-info btn-large" value="Submit"/>
          </form>
        </div>
      </div>
    </div>

<!-- Second Step (Choose Color of Shoe Base) -->

    <div class="text-center" id="second-step">
      <span id="insertname"></span>
      <br>
      <p class="lead"><br> How would you describe yourself?</p>
      <form class="" action="index.html" method="post" id="base-color-form">

        <br>
        <div class="row justify-content-center well">
            <div class="col-md-2 radio">
              <label>
                <input type="radio" name="base-color" value="white" checked>
                <br>Class
              </label>
            </div>
            <div class="col-md-2 radio">
              <label>
                <input type="radio" name="base-color" value="blue" >
                <br>Gentleman
              </label>
            </div>
            <div class="col-md-2 radio">
              <label>
                <input type="radio" name="base-color" value="black" >
                <br>Stealth
              </label>
            </div>
            <div class="col-md-2 radio">
              <label>
                <input type="radio" name="base-color" value="red" >
                <br>Passionate
              </label>
            </div>
        </div>
        <br><br>
        <input type="submit" class="btn btn-info btn-large" value="Submit"/>
      </form>
    </div>

<!-- Third Step (Show Shoe Selection) -->
<div class="text-center" id="third-step">
  <h1>You selected <span id="shoe-personality"></span>.</h1>
  <br>
  <p class="lead">Let's start with the base. How do you feel about a <span id="shoe-color-word"></span> shoe?</p>
  <br><br>

<!-- Four Shoe Color Options -->

    <div id="white-shoe">
      <img src="/static/img/shoes/white.png" alt="white-shoe" class="resize-shoe" >
    </div>
    <div id="blue-shoe">
      <img src="/static/img/shoes/blue.png" alt="blue-shoe" class="resize-shoe" >
    </div>
    <div id="black-shoe">
      <img src="/static/img/shoes/black.png" alt="black-shoe" class="resize-shoe" >
    </div>
    <div id="red-shoe">
      <img src="/static/img/shoes/red.png" alt="red-shoe" class="resize-shoe" >
    </div>
  <br>

<!-- Yes / No buttons -->

  <div class="row justify-content-center">
    <div class="col-md-3">
      <input class="btn btn-info btn-large" value="I Like It!" id="like-it"/>
    </div>
    <div class="col-md-3">
      <input class="btn btn-danger btn-large" value="Try again" id="try-again"/>
    </div>
  </div>

  </div>

<!-- Fourth Step (Fine Tune Customization) -->

    <div class="text-center" id="fourth-step">
      <span id="fourth-step-h1"></span>
      <p class="lead">I have just a few more questions for you.</p>
      <form action="submit" method="post" id="final-customization">
        <div class="row">
          <div class="col-md-3">
            <label for="location">My favorite fruit is:</label>
            <div class="selectWrapper">
              <select id="fruit">
                  <option value="red">Strawberry</option>
                  <option value="orange">Oranges</option>
                  <option value="yellow">Bananas</option>
              </select>
            </div>

          </div>
          <div class="col-md-3">
            <label for="location">Come find me:</label>
            <div class="selectWrapper">
              <select id="location">
                  <option value="black">Outdoors</option>
                  <option value="white">Indoors</option>
              </select>
            </div>
          </div>
          <div class="col-md-3">
            <label for="location">Besties:</label>
            <div class="selectWrapper">
              <select id="friends">
                  <option value="white">Straightforward</option>
                  <option value="pink">Fun and Bubbly</option>
                  <option value="black and white">Exclusive</option>
              </select>
            </div>
          </div>
        <div class="col-md-3">
          <label for="location">Deep down I am:</label>
          <div class="selectWrapper">
            <select id="deepdown">
                <option value="white">Lighthearted</option>
                <option value="black and white">Adaptable</option>
                <option value="lime green">Unique</option>
                <option value="red">Calm</option>
            </select>
          </div>
        </div>
        </div>
        <br>
        <div class="row justify-content-center">
          <div class="col-md-3">
            <input type="submit" class="btn btn-info btn-large" value="Submit!" id="submit-answers"/>
          </div>
        </div>
      </form>

    </div>

    <div class="text-center" id="fifth-step">
      <h1>Here you go, <span id="final-user-name"></span>.</h1>
      <p class="lead">This shoe would look great on you!</p>
      <div class="row justify-content-center">
        <div class="col-md-4">
          <div class="card" style="width: 20rem;">
            <span id="final-featured-shoe"></span>
            <div class="card-block">
              <h4 class="card-title"><span id="final-user-name-h4"></span>'s Custom Shoe</h4>
              <p class="card-text">As you know, it will have a <span id="final-color"></span> color for the base.</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-center">Your shoelaces will be &nbsp<span id="final-shoelaces"></span></li>
              <li class="list-group-item text-center">Your webbings will be &nbsp<span id="final-webbings"></span></li>
              <li class="list-group-item text-center">Your midsole will be &nbsp<span id="final-midsole"></span></li>
              <li class="list-group-item text-center">Your outsole will be &nbsp<span id="final-outsole"></span></li>
            </ul>
            <div class="card-block">
              <div class="row">
                <div class="col-md-6">
                  <a href="http://www.adidas.com/us/customize"><button class="btn btn-info btn-large">Purchase</a>
                </div>
                <div class="col-md-6">
                  <button class="btn btn-danger btn-large" id="startover">Start Over</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
      <br><br>
  </div>








<div id="about" class="team-section">
  <h1>Our Team</h1>
  <span class="border"></span>
  <div class="ps">
    <a href="#p1"><img id="port1" src="/static/images/kingjosh.jpeg" alt=""></a>
    <a href="#p2"><img id="port2" src="/static/images/yussuf.png" alt=""></a>
    <a href="#p3"><img id="port3" src="/static/images/abdul.jpg" alt=""></a>
    <a href="#p5"><img id="port5" src="/static/images/miano.jpg" alt=""></a>

  </div>

  <div class="section" id="p1">
    <span class="name">King Josh</span>
    <span class="border"></span>
    <p>Scrum Master</p>
  </div>

    <div class="section" id="p2">
      <span class="name">Yussuf</span>
      <span class="border"></span>
      <p>Front-end(Graphics and Design) </p>
    </div>

      <div class="section" id="p3">
        <span class="name">John</span>
        <span class="border"></span>
        <p>Back-end(Graphics and Design)</p>
      </div>

      <div class="section" id="p5">
        <span class="name">Ryan</span>
        <span class="border"></span>
        <p>Front-end(Graphics and Design)</p>
      </div>

</div>
<section class="page-section spad contact-page">
    <div class="container">
      <div class="map" id="map-canvas"></div>
</div>
</section>
<footer class="foot">
  

<div id="contact">
<h1 class="head4">Contact</h1>
<span class="border1"></span>
<p class="para1">Feel free to follow our socials to keep up to date with us.</p>
<div class="container">
      <div class="row row1 justify-content-between">
          <div class="col">
            <img class="twitter" src="/static/images/social_icons/twitter.png">
          </div>
          <div class="col">
            <img class="fb" src="/static/images/social_icons/facebook.png">
          </div>
          <div class="col">
            <img class="pin" src="/static/images/social_icons/pinterest.png">
          </div>
          <div class="col">
            <img class="ig" src="/static/images/social_icons/instagram.png">
          </div>
            <!-- load for map -->
 

        </div>
        </div>
      </div>


</footer>

<div class="mapouter" style="margin-top: 100px; width: 100px;"><div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=kenya&t=k&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.embedgooglemap.net/blog/best-wordpress-themes/">wordpress template</a></div><style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style></div>
{% endblock%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
   <div class="container-fluid">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="/"> <h2 style="text-align: center;font-family: 'Luckiest Guy', cursive; letter-spacing: 4px; font-size: 3.5em; font-weight: bolder">M<span style="color: crimson">Y</span>SHOE<span style="color: crimson">S</span></h2></a>
      </div>
      <div class="navbar">
         <ul style="color: red;">
            <li style="color: red;"><a href="/" style="margin-top: 50px">Home</a></li>
            <li><a href="/abo.html" style="margin-top: 50px">About us</a></li>
         </ul>
      </div>


      <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.search')}}"style="margin-top: 50px">SHop</a></li>

      <li><a href="{{url_for('main.index',uname=current_user.username)}}">Profile</a></li>
      <li style="color:white;padding:15px;">{{current_user.username}}</li>
      <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}
      <li ><a href="{{url_for('auth.login')}}">Sign in</a></li>
      {%endif%}
    </ul>


   </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  
  <div class="col-md-4">
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
    
  </div>

</div>


  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/search.html
<!-- {% extends 'index.html'%} -->
{% import 'macros.html' as macro%}


  {% block styles%}
  {{ super() }}
  <link href="https://fonts.googleapis.com/css?family=Advent+Pro&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="animate.css">
  <link rel="stylesheet" href="{{url_for('static',filename='css/animate.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename='css/hover.css')}}">s


  {% endblock %}


{% block content %}
<h2 id="head1">
  <a href="{{url_for('main.first')}}"><img src="/static/images/y.jpg" id="slideimg1"/ style="width: 200px;height: 100px;" class="hvr-grow"></a>
</h2>
<div class="container-fluid">
	

  <div class="row">
    <div class="col-md-6">
     <a href="{{url_for('main.first')}}"><img src="static/images/vapoor.png" style="width: 600px;height: 500px;" class="hvr-grow"></a>
   </div>
   <div class="col-md-6">

    <a href="{{url_for('main.first')}}"> <img src="static/images/max3.jpg" style="width: 600px;height: 400px;margin-top: 50px;" class="hvr-grow"></a>

  </div>
  
</div>



<div class="row">
  <div class="col-md-6">
   <a href="second.html"> <img src="static/images/b.jpg" style="width: 500px;height: 500px" class="hvr-grow"></a>
 </div>
 <div class="col-md-6">

  <a href="second.html"> <img src="static/images/yuuu.jpg" style="width: 500px;height: 500px" class="hvr-grow"></a>

</div>

</div>



<div class="opp">
  <div class="row">
    <div class="col-md-6">
     <a href="third.html"> <img src="static/images/green.png" style="width: 80%;height: 80%;"class="hvr-grow"></a>
   </div>
   <div class="col-md-6">

    <a href="third.html"> <img src="static/images/nike.png" style="width: 80%;height: 80%"class="hvr-grow"></a>

  </div>
  
</div>
</div>


<div class="op">
  <div class="row">
    <div class="col-md-6">
     <a href="fourth.html"> <img src="static/images/oo.jpg" style="width: 70%;height: 70%;"class="hvr-grow"></a>
   </div>
   <div class="col-md-6">

    <a href="fourth.html"> <img src="static/images/n.jpg" style="width: 65%;height: 65%"class="hvr-grow"></a>

  </div>
  
</div>
</div>




</div>
{% endblock %}